namespace FormulaBoss.Runtime;

/// <summary>
///     Marks a public method or property for inclusion in synthetic intellisense types
///     generated by <c>TypedDocumentBuilder</c>.
/// </summary>
[AttributeUsage(AttributeTargets.Method | AttributeTargets.Property)]
public sealed class SyntheticMemberAttribute : Attribute;

/// <summary>
///     Declares a collection class for synthetic type generation, specifying the element type
///     so the builder knows which <c>dynamic</c> → typed substitution to apply in lambda parameters.
/// </summary>
[AttributeUsage(AttributeTargets.Class)]
public sealed class SyntheticCollectionAttribute : Attribute
{
    /// <summary>The runtime element type (e.g. <c>typeof(Row)</c> for <c>RowCollection</c>).</summary>
    public Type ElementType { get; set; } = null!;
}

/// <summary>
///     Marks a public method or property as intentionally excluded from synthetic types.
///     Prevents the sync test from flagging it as missing <see cref="SyntheticMemberAttribute" />.
/// </summary>
[AttributeUsage(AttributeTargets.Method | AttributeTargets.Property)]
public sealed class SyntheticExcludeAttribute : Attribute;
